### ISSUE TITLE
最新版本的启动器的自定义Java不工作

### ISSUE THREAD

**Issue by dongffan** [SolitudeSun/Minecraft-Server-Launcher#8]
如标题所示

复现步骤：
启动启动器 让它生成`设置.ini`(如果已经存在则忽略)
打开`设置.ini`，修改`使用默认Java`选项为关
在`Java路径`选项，填写一个有效的路径(例如`C:\Program Files\Zulu\zulu-17\bin\java.exe`)
重新启动启动器，会提示`警告：未检测到C:\Program Files\Zulu\zulu-17\bin\java.exe路径下的Java，请在'设置.ini'中重新设置Java路径！`

**Comment by SolitudeSun** [comment]
@dongffan 已在 [v5.2.2](https://github.com/SolitudeSun/Minecraft-Server-Launcher/releases/tag/v5.2.2) 版本中修复
